name: opencap_clean
channels:
  - opensim-org
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5
  - aom=3.12.1
  - blas=1.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - cffi=1.17.1
  - contourpy=1.2.1
  - cycler=0.12.1
  - dav1d=1.2.1
  - expat=2.7.3
  - ffmpeg=6.1.1
  - fontconfig=2.15.0
  - fonttools=4.59.1
  - freeglut=3.2.2
  - freetype=2.14.1
  - glib=2.86.3
  - glib-tools=2.86.3
  - graphite2=1.3.14
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - h2=4.2.0
  - harfbuzz=10.4.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icc_rt=2022.1.0
  - icu=75.1
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - intel-openmp=2023.2.0
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libclang13=21.1.8
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libglib=2.86.3
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - libogg=1.3.5
  - libpng=1.6.54
  - libsqlite=3.51.2
  - libtheora=1.2.0
  - libtiff=4.7.0
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - mkl=2023.2.0
  - mkl-service=2.4.1
  - munkres=1.1.4
  - openjpeg=2.5.3
  - opensim=4.5.1
  - openssl=3.6.1
  - packaging=26.0
  - pcre2=10.46
  - pillow=11.3.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.3.8
  - ply=3.11
  - pooch=1.8.2
  - pthread-stubs=0.4
  - pycparser=2.22
  - pyparsing=3.2.3
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pysocks=1.7.1
  - python=3.9.25
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2025.2
  - pyyaml=6.0.2
  - qt-main=5.15.15
  - requests=2.32.5
  - setuptools=80.9.0
  - sip=6.10.0
  - six=1.17.0
  - sqlite=3.51.1
  - tbb=2021.13.0
  - tk=8.6.15
  - toml=0.10.2
  - tomli=2.2.1
  - tornado=6.5.2
  - tzdata=2025c
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - yaml=0.2.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - astunparse==1.6.3
      - boto3==1.42.39
      - botocore==1.42.39
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - exceptiongroup==1.3.1
      - fastapi==0.128.8
      - ffmpeg-python==0.2.0
      - flatbuffers==25.12.19
      - future==1.0.0
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.14.0
      - humanfriendly==10.0
      - idna==3.11
      - importlib-metadata==8.7.1
      - jmespath==1.1.0
      - keras==3.10.0
      - libclang==18.1.1
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - maskpass==0.3.7
      - matplotlib==3.5.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - namex==0.1.0
      - narwhals==2.16.0
      - numpy==1.21.6
      - onnxruntime==1.19.2
      - opencv-python-headless==4.13.0.90
      - opt-einsum==3.4.0
      - optree==0.18.0
      - pandas==1.3.5
      - plotly==5.11.0
      - protobuf==6.33.5
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pynput==1.8.1
      - pyreadline3==3.5.4
      - python-decouple==3.8
      - rich==14.3.1
      - s3transfer==0.16.0
      - scipy==1.7.3
      - starlette==0.49.3
      - sympy==1.14.0
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - tqdm==4.67.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==1.26.20
      - uvicorn==0.39.0
      - werkzeug==3.1.5
      - wrapt==2.0.1

